//AREAS
export const FETCH_AREAS_REQUEST = 'FETCH_AREAS_REQUEST';
export const FETCH_AREAS_SUCCESS = 'FETCH_AREAS_SUCCESS';
export const FETCH_AREAS_FAILURE = 'FETCH_AREAS_FAILURE';
export const ADD_AREAS_REQUEST = 'ADD_AREAS_REQUEST';
export const ADD_AREAS_SUCCESS = 'ADD_AREAS_SUCCESS';
export const ADD_AREAS_FAILURE = 'ADD_AREAS_FAILURE';
export const DELETE_AREAS_REQUEST = 'DELETE_AREAS_REQUEST';
export const DELETE_AREAS_SUCCESS = 'DELETE_AREAS_SUCCESS';
export const DELETE_AREAS_FAILURE = 'DELETE_AREAS_FAILURE';
export const UPDATE_AREAS_REQUEST = 'UPDATE_AREAS_REQUEST';
export const UPDATE_AREAS_SUCCESS = 'UPDATE_AREAS_SUCCESS';
export const UPDATE_AREAS_FAILURE = 'UPDATE_AREAS_FAILURE';